spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task2_db
    username: postgres
    password: 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        jdbc:
          lob:
            non_contextual_creation: true
  sql:
    init:
      mode: never

dataLoaderMode: never  #always bo'lsa proekt run bo'lganda avtamat bazaga malumot qo'shadi(role, permission va h.k)


